### ISSUE TITLE
Breaks on npm install

### ISSUE THREAD

**Issue by mikeCm14** [robsonos/serialportronic#18]
Hello,

I'm trying to run this project but fails on `npm install`. Is there a particular branch that's being maintained? Thanks

**Comment by robsonos** [comment]
Hi @Heckthor,

What error are you getting?

**Comment by sohitrajput** [comment]
I'm trying to run this project but fails on npm install. error occur while npm install 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:472:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\oqi003\Desktop\ionic electron\serialportronic\node_modules\@serialport\bindings        
gyp ERR! node -v v14.21.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

**Comment by sohitrajput** [comment]
I am using ionic 6 cli and node version 14.21.0 so can you help me

**Comment by mikeCm14** [comment]
At the risk of stating the obvious, by looking at your log, you need to install Python. Have you done that?

**Comment by abhinavs97** [comment]
> @serialport/bindings@2.0.8 install C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=16.19.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
(node:11880) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(329): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(330): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(331): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(378): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings
gyp ERR! node -v v16.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\electron-reload\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2023-06-19T11_51_11_579Z-debug.log

Getting this error at the time while doing npm install. I am using ionic 6 cli and node version 16.19.1. @Heckthor @robsonos

**Comment by abhinavs97** [comment]
Breaks at the time npm install.
Using ionic 6 cli and node 16.19.1

logs:-

> @serialport/bindings@2.0.8 install C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=16.19.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
(node:12212) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(329): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(330): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(331): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\dell\downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\src\serialport.cpp(378): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dell\Downloads\serialportronic\serialportronic\node_modules\@serialport\bindings
gyp ERR! node -v v16.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN @ionic-native/core@5.16.0 requires a peer of rxjs@^5.5.0 || ^6.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\electron-reload\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2023-06-19T13_07_11_898Z-debug.log

@Heckthor @robsonos

**Comment by robsonos** [comment]
Hi all.

I have made some changes to the code. Make sure you are using Node 12 and @ionic/cli@6, as per [prerequisites](https://github.com/robsonos/serialportronic#prerequisites).

Cheers

**Comment by sohitrajput** [comment]
Hi Robson.

I want to use the serialport library in my ionic angular project so what
should I need to do?
 In which i am using
 Ionic CLI                     : 6.20.4
***@***.***\cli)
   Ionic Framework               : @ionic/angular 6.6.3
   @angular-devkit/build-angular : 14.2.11
   @angular-devkit/schematics    : 14.2.11
   @angular/cli                  : 14.2.11
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v14.21.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.17
   OS     : Windows 10

**Comment by robsonos** [comment]
If you want to use seriaport with angular >9 you will have to use [electron's IPC](https://www.electronjs.org/docs/latest/tutorial/ipc)

**Comment by sohitrajput** [comment]
So there is no solution of integration serialport ? if no so, can you
give me another library example.

**Comment by robsonos** [comment]
Hi @Heckthor @sohitrajput @abhinavs97,

I am archiving this repo now. If you want a more modern solution please check out my new repo [spie](https://github.com/robsonos/spie).

Cheers
